baseURL = "https://theoriz0.github.io/"
languageCode = "zh-cn"
title = "theoriz0's blog"
theme = "hugo-theme-stack"

disqusShortname = "theoriz0blog"
googleAnalytics = "G-8HN1FE064R"

hasCJKLanguage = true

[params]
mainSections = ["posts"]

    [params.sidebar.avatar]
    enabled = false

  [params.article]
  math = false
  toc = true
  readingTime = false

  [params.widgets]
  homepage = [ ]
  page = [{ type = "toc"}]

  [params.comments]
  enabled = true
  provider = "disqus"