baseURL = "http://theoriz0.github.io/"
languageCode = "zh-cn"
title = "theoriz0's blog"
theme = "terminal"
disqusShortname = "theoriz0blog"
googleAnalytics = "G-8HN1FE064R"

[params]
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # center theme with default width
  centerTheme = true

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = true

  # set all headings to their default size (depending on browser settings)
  oneHeadingSize = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  TocTitle = "内容大纲" # default

[languages]
  [languages.en.params.logo]
    logoText = "theoriz0's blog"
    logoHomeLink = "/"